receivers:
  otlp:
    protocols: # enable OpenTelemetry Protocol receiver, both gRPC and HTTP
      grpc:
        endpoint: 0.0.0.0:4317
      http:
        endpoint: 0.0.0.0:4318

exporters:
  otlp/jaeger: # export received traces to Jaeger
    endpoint: jaeger:4317 # grpc endpoint
    tls:
      insecure: true

extensions:
  health_check:
    endpoint: 0.0.0.0:13133
    path: "/health"

processors:
  batch:
    timeout: 0 # send data immediately

service:
  extensions: [health_check]
  pipelines:
    traces:
      receivers: [otlp]
      processors: [batch]
      exporters: [otlp/jaeger]